spring:
  datasource:
    url: jdbc:mysql://localhost:3306/<nome_do_banco_de_dados>
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: <usuario_do_banco_de_dados>
    password: <senha_do_banco_de_dados>
  jpa:
    hibernate:
      ddl-auto: update